### PR TITLE
feature: add link card container (close #36)

### LINKED ISSUE #36: 大佬有没有考虑加一个文章内的 链接卡片 语法
如题

### PR DESCRIPTION
**Pull request by Zhengqbbb**
issue: https://github.com/Renovamen/vuepress-theme-gungnir/issues/36

## markdown container syntax
```md
::: link {Icon Name | Image URL} [title](url)
description
:::
```

## demo
image

### CODE REVIEW

**Comment by Renovamen** [comment]
Thanks! I'll review it in the next week!

**Comment by Renovamen** [comment]
Looks great, thank you!

What do you think about making link card container a plugin?

**Comment by Zhengqbbb** [comment]
> What do you think about making link card container a plugin?

@Renovamen That's what I thought at the beginning, but I thought about some of the independence and light weight of this plugin, it needs to depend on a bit more, but I can still try it out on the weekend.

**Comment by Zhengqbbb** [comment]
@Renovamen I recently tried to encapsulate with plugin, and repetitive code, such as autolink, vicon and container, appeared for the sake of plugin independence. It made me realize that it's not very good. I think it's better to put it in the theme. What do you think?

**Comment by Renovamen** [comment]
@Zhengqbbb I see, I think you are right, I overlooked this problem. I'll merge it, thanks a lot!

**Pull request merged**
